% NAFFLIB
% See also 
% 
%   Contents file for NAFFLIB and its subfolders.
%   
%   NAFFLIB
%   calcnaff     - Computes NAFF decomposition for a phase space trajectory
%   naff_cc      - Compile nafflibrary for Matlab
%   naff_example - Example to test naff within matlab
%   nafflib      - MATLAB to NAFF library
%    
%   This file was generated by updateContents.m on 05 Nov 2023 at 22:34:12.
