% NAFF frequency analysis
%
%   Contents file for NAFFLIB and its subfolders.
%   
%   NAFFLIB
%   calcnaff     - Computes NAFF decomposition for a phase space trajectory
%   naff_cc      - Compile nafflibrary for Matlab
%   naff_example - Example to test naff within matlab
%   nafflib      - MATLAB to NAFF library
%    
%   This file was generated by updateContents.m on 27 Jun 2025 11:30:50.
