% ORBIT
% See also 
% 
%   Contents file for ORBIT and its subfolders.
%   
%   ORBIT
%   findorbit     - Find the closed orbit
%   findorbit4    - Finds closed orbit in the 4-d transverse phase
%   findorbit6    - Finds closed orbit in the full 6-d phase space
%   findsyncorbit - Finds closed orbit, synchronous with the RF cavity
%   plotcod       - Closed Orbit Distortion
%   xorbit_6      - Private function used by findorbit6
%   xorbit_ct     - Private function used by findsyncorbit
%   xorbit_dp     - Private function used by findorbit4
%    
%   This file was generated by updateContents.m on 06 Nov 2023 at 14:58:12.
