% Closed orbit search
%
%   Contents file for ORBIT and its subfolders.
%   
%   ORBIT
%   findorbit     - Find the closed orbit
%   findorbit4    - Finds closed orbit in the 4-d transverse phase
%   findorbit6    - Finds closed orbit in the full 6-d phase space
%   findsyncorbit - Finds closed orbit, synchronous with the RF cavity
%   plotcod       - Plots the closed orbit distortion
%   xorbit_6      - Private function used by findorbit6
%   xorbit_ct     - Private function used by findsyncorbit
%   xorbit_dp     - Private function used by findorbit4
%    
%   This file was generated by updateContents.m on 27 Jun 2025 11:52:47.
