% ATMATCH
% See also 
% 
%   Contents file for ATMATCH and its subfolders.
%   
%   ATMATCH
%   atApplyVariation           - Applies a series of variations to variables as described in
%   atDisplayConstraintsChange - This funciton evaluates the contraints defined in Constraints for lattice
%   atDisplayVariableChange    - This functions retrives variable Values for two rings to compare
%   atEvaluateConstraints      - This funciton evaluates the contraints defined in Constraints for lattice
%   atGetPenalty
%   atGetVariableValue
%   atlinconstraint            - Generate a constraint on linear optics for atmatch
%   atmatch                    - Function [..
%   atVariableBuilder          - AtVarBuilder   create a simple variable structure for use with atmatch
%    
%   This file was generated by updateContents.m on 06 Nov 2023 at 14:58:12.
