[build-system]
requires = [
    "numpy == 1.16.6;python_version<'3.10'",
    "numpy == 1.21.5;python_version>='3.10'",
    "setuptools >= 45",
    "setuptools_scm>=6.2",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
# Pypy does not have Scipy so we cannot support it.
build = ["cp3{6,7,8,9,10}*"]
build-verbosity = "1"
# "build" frontend fails on windows
# build-frontend = "build"

[tool.cibuildwheel.macos]
archs = ["x86_64", "arm64"]

[tool.setuptools_scm]
root = ".."
# write_to = "pyat/at/_version.py"
git_describe_command = "git describe --tags --long --match pyat-[0-9]* HEAD"
fallback_version = "0.0.0"
