function varargout = atbaseplot(varargin)
%ATBASEPLOT Plots data generated by a user-supplied function
%
%ATBASEPLOT             Plots THERING in the current axes
%
%ATBASEPLOT(RING)       Plots the lattice specified by RING
%
%ATBASEPLOT(RING,DPP)   Plots at momentum deviation DPP (default: 0)
%
%ATBASEPLOT(...,[SMIN SMAX])  Zoom on the specified range
%
%ATBASEPLOT(...,@PLOTFUNCTION,PLOTARGS)
%   PLOTFUNCTION: User supplied function providing the values to be plotted
%   PLOTARGS:     Optional cell array of arguments to PLOTFUNCTION
%   PLOTFUNCTION is called as:
%   [S,PLOTDATA]=PLOTFUNCTION(RING,DPP,PLOTARGS{:})
%
%       S:        longitudinal position, length(ring)+1 x 1
%       PLOTDATA: structure array,
%         PLOTDATA(1) describes data for the left (main) axis
%           PLOTDATA(1).VALUES: data to be plotted, length(ring)+1 x nbcurve
%           PLOTDATA(1).LABELS: curve labels, cell array, 1 x nbcurve
%           PLOTDATA(1).AXISLABEL: string
%         PLOTDATA(2) optional, describes data for the right (secondary) axis
%
%ATBASEPLOT(...,'OptionName',OptionValue,...) Available options:
%   'synopt',true|false         Plots the lattice elements
%   'labels',REFPTS             Display the names of selected element names
%   'index',REFPTS             Display the index of selected element names
%   'leftargs',{properties}     properties set on the left axis
%   'rightargs',{properties}    properties set on the right axis
%   'KeepAxis'                  flag to keep R1,R2,T1,T2 at each slice in
%                               detailed plots (mandatory with vert. bend).
%
%ATBASEPLOT(AX,...)     Plots in the axes specified by AX. AX can precede
%                       any previous argument combination
%
%CURVE=ATBASEPLOT(...)  Returns handles to some objects:
%   CURVE.PERIODICIY ring periodicity
%   CURVE.LENGTH    structure length
%   CURVE.DPP       deltap/p
%   CURVE.LEFT      Handles to the left axis plots
%   CURVE.RIGHT     Handles to the right axis plots
%   CURVE.LATTICE   Handles to the Element patches: structure with fields
%          Dipole,Quadrupole,Sextupole,Multipole,BPM,Label
%

global THERING %#ok<GVMIS>

% Select axes for the plot
[ax,args]=getargs(varargin,[],'check',@(x) isscalar(x) && ishandle(x));
if isempty(ax), ax=gca; end

% Select the lattice
[ring,args]=getargs(args,THERING,'check',@iscell);
args=getdparg(args);
[varargout{1:nargout}]=wrapper6d(ring,@xplot,ax,args{:});
end
