% ATPLOT
% See also 
% 
%   Contents file for ATPLOT and its subfolders.
%   
%   ATPLOT
%   atbaseplot             - Plots data generated by a user-supplied function
%   atplot                 - Plots optical functions
%   atplotsyn              - Helper function for ATPLOT
%   atreforbit             - Keep track of the nominal reference orbit through displaced elements
%   xplot                  - Private function used by atplot and atbaseplot
%   
%   ATPLOT/PLOTFUNCTIONS
%   CurlyH                 - Function [H,Hv]=CurlyH(RING,dp,ind)
%   CurlyHlindata          - Function [H,Hv]=CurlyHlindata(lindata)
%   plBeamSize             - Plot H and V beam size
%   plClosedOrbit          - Plots H and V 4x4 closed orbit
%   plCorrectorStrength    - Plot PolynomB
%   plEmitContrib          - Plot H/rho³ at every dipole
%   plenvelope             - Plot beam envelope
%   plot_betabeat          - Function plot_betabeat(THERING_ref,THERING_mod)
%   plot_trajectory        - Plots particle trajectories
%   plotAperture           - Plots x and y aperture
%   plotB0curlyh           - Plot B and H
%   plotbetadisp           - Function [s,plotdata]=plotbetadisp(ring,dpp,plotfun,varargin)
%   plotbetadispcurlyh     - Plot beta, dispersion and H
%   plotERAperture         - Plot RApertures EApertures
%   plotRDT
%   plotsqrtbetadispcurlyh - Plot sqrt(beta), dispersion and H
%   plotWdispP             - Plot W functions
%   plPolynomBComp         - PlotBn coefficient with normalization
%   plPolynomBSxtOct       - Plots Bn for sextupole and octupole magnets
%   plSigmaSigmap          - Plots beam sizes and divergences
%   pltouschek             - Plots Touschek lifetime contribution
%   plxi                   - #ok<INUSD>
%    
%   This file was generated by updateContents.m on 06 Nov 2023 at 14:58:12.
