% LATTICE_TOOLS
% See also 
% 
%   Contents file for LATTICE_TOOLS and its subfolders.
%   
%   LATTICE_TOOLS
%   atreadbeta     - Reads a BETA file
%   atsetglobval   - Creates the global variable GLOBVAL and adds Energy
%   scalesext      - Newring=scalesext(ring,sextfam,scale)
%   setsext        - Newring=setsext(ring,fam,val);
%   setsextall     - Newring=setsextall(ring,fam,val);
%   sext_sens_scan - Esrf(:)
%    
%   This file was generated by updateContents.m on 06 Nov 2023 at 14:58:13.
