% LOCAL_LATTICE_PARAMS
% See also 
% 
%   Contents file for LOCAL_LATTICE_PARAMS and its subfolders.
%   
%   LOCAL_LATTICE_PARAMS
%   atmakeXYProjectionEllipse - Gives points to plot the contour ellipses
%   machine_at                - Machine AT will return the optics of the lattice. Essentially takes what
%   plotContours              - Plots contours
%    
%   This file was generated by updateContents.m on 06 Nov 2023 at 14:58:13.
