% LONGITUDINALDYNAMICS
% See also 
% 
%   Contents file for LONGITUDINALDYNAMICS and its subfolders.
%   
%   LONGITUDINALDYNAMICS
%   atBunchLength    - Bunch length due to the potential well effect
%   atRFacc          - Computes RF acceptance of the ring
%   atsetcavity      - ATSECAVITY Set the parameters of RF cavities
%   atSetCavityPhase - SETCAVITYPHASE     Set the TimeLag attribute of RF cavities
%   BunchLength      - Bunch length due to the potential well effect
%   cavityoff        - Turns cavities OFF
%   cavityon         - Turns Cavities ON
%   mcf              - Momentum compaction factor
%   nus              - Computes synchrotron tune from RF parameters
%   phis             - Phase = phis(U0MeV,VrfMV)
%   RFacc            - Computes the RF acceptance with linear formula
%    
%   This file was generated by updateContents.m on 06 Nov 2023 at 14:58:12.
