% LINEAROPTICS
% See also 
% 
%   Contents file for LINEAROPTICS and its subfolders.
%   
%   LINEAROPTICS
%   amat                        - Find A matrix from one turn map matrix T such that:
%   atdampingrates              - Find tunes and damping rates from one map matrix with radiation
%   atlinopt                    - Performs 4D linear analysis of the COUPLED lattices
%   atlinopt2                   - Performs the linear analysis of UNCOUPLED lattices
%   atlinopt4                   - Performs the 4D linear analysis of COUPLED lattices
%   atlinopt6                   - Performs linear analysis of the lattice
%   beam22                      - Computes the beam matrix from the 1-turn transfer matrix
%   beam44                      - Computes the coupled beam matrices
%   find_betaoids               - [H1 H2 H3]=find_betaoids(A)
%   find_etaoids                - Given the normalizing matrix A, we compute the etaoids
%   find_inv_G                  - This function computes the invariants of a one turn map matrix
%   find_inv_G_fromA            - This function computes the invariant matrices G1,G2,G3
%   findelemm44                 - Numerically finds the 4x4 transfer matrix of an element
%   findelemm66                 - Numerically finds the 6x6 transfer matrix of an element
%   findm44                     - Numerically finds the 4x4 transfer matrix of an accelerator lattice
%   findm66                     - Numerically finds the 6x6 transfer matrix of an accelerator lattice
%   get_dispersion_from_etaoids - Computes dispersion functions (x,px,y,py) at refpts
%   jmat                        - Compute antisymmetric Matrix [O 1; -1 0]
%   linopt                      - Performs linear analysis of the COUPLED lattices
%   mkSRotationMatrix           - (PSI) coordinate transformation matrix
%   plotbeta                    - Plots UNCOUPLED! beta-functions
%   r_analysis                  - Return the phase for A standardization
%    
%   This file was generated by updateContents.m on 06 Nov 2023 at 14:58:12.
