% ATUTILS
% See also 
% 
%   Contents file for ATUTILS and its subfolders.
%   
%   ATUTILS
%   atoptions         - Definition of default parameters
%   frequency_control - Private. Handle off-momentum for 6D lattice
%   getargs           - Process positional arguments from the input arguments
%   getdparg          - Handle positional dp arguments
%   getenvopt         - (NAME, DEFAULTVALUE)
%   getflag           - Check the presence of a flag in an argument list
%   getoption         - Extract a keyword argument from an argument list
%   opticsoptions     - (private) extract arguments for atlinopt
%   parseargs         - Check and expands optional argument lists
%   setoption         - Set AT preference values
%   wrapper6d         - Private. Handle off-momentum for 6D lattice
%    
%   This file was generated by updateContents.m on 06 Nov 2023 at 14:58:12.
