% CREATE_ELEMS
% See also 
% 
%   Contents file for CREATE_ELEMS and its subfolders.
%   
%   CREATE_ELEMS
%   atidtable_dat - Atidtable(FamName, Nslice, filename, Energy, method)
%    
%   This file was generated by updateContents.m on 06 Nov 2023 at 14:58:13.
