% CONVERTERS
% See also 
% 
%   Contents file for CONVERTERS and its subfolders.
%   
%   CONVERTERS
%   readmad                    - Reads the file output of MAD commands
%   
%   CONVERTERS/AT2ELEGANT
%   AT_2_Elegant               - This functions converts the AT lattice AT_ring in elegant form
%   
%   CONVERTERS/AT2G4BL
%   ATtoG4BL                   - Function [outtext]=ATtoG4BL(P_0,particle,folder)
%   
%   CONVERTERS/AT2MAD8
%   AT_2_mad8                  - Function [elelat,def,lines]=AT_2_mad8(AT_ring,linename)
%   
%   CONVERTERS/AT2MADX
%   AT_2_madX                  - Function [elelat,defs,lines]=AT_2_madX(AT_ring,linename)
%   
%   CONVERTERS/AT2OPA
%   AT_2_OPA                   - Function AT_2_OPA(AT_ring,linename)
%   
%   CONVERTERS/ELEGANT2AT
%   ele2at_run_me              - Test_elegant_converter
%   elegant2at                 - Function elegant2at(elegantlattice,E0,outfilename)
%   ParseAtributesELEGANT_2_AT - Determines atribute and sets field in sxs{i} structure AT
%   
%   CONVERTERS/MAD82MADX
%   mad8TOmadx                 - Converts mad8 sequence files to madX
%   
%   CONVERTERS/MADX2AT
%   atfrommadx                 - Function atfrommadx(seqfilemadX,E0,outfilename)
%   buildATLattice             - Given a list (cell array) of elements with specified field Spos (center of element (madx default)) in a
%   ParseAtributesMADX_2_AT    - Determines atribute and sets field in sxs{i} structure AT
%   reshapeToCellArray         - If CEL_CEL is a cell array of structures and cell arrays it converts it a
%   
%   CONVERTERS/MADX2AT/EXAMPLES
%   convertMADXtoATExample     - Simple lattice test (uncomment to run)
%   
%   CONVERTERS/MADX2G4BL
%   madx2g4bl                  - Function [outtext]=madx2g4bl(P_0,particle,folder)
%    
%   This file was generated by updateContents.m on 06 Nov 2023 at 14:58:13.
