function arc1=MatchQuadLengthForEqualK1(arc,d)
% adjusts length of QFA6 QFA8 to have the same K1
indQF=findcells(arc,'FamName','QF');
indQFM=findcells(arc,'FamName','QFM');
indQD=findcells(arc,'FamName','QD');
indQDM=findcells(arc,'FamName','QDM');

arc=matchingDBA(arc,17.3,0.58,0.0,0.35,...
    indQF,indQD,indQFM,indQDM);

Variab1=atVariableBuilder(arc,...
    {@(ar,dl)VaryMagLength(ar,dl,indQF,indQFM)},{0.001});

% empty varaible. Performs rematch at every iteration of the minimizer
Variab2=atVariableBuilder(arc,...
    {@(r,~)matchingDBA(r,17.3,0.58,0.0,0.35,...
    indQF,indQD,indQFM,indQDM)},{[]});

Variab=[Variab1, Variab2];

%% constraints
Constr=struct(...
    'Fun',@(r,~,~)compK1(r,indQFM,indQF),...
    'Min',d,...
    'Max',d,...
    'RefPoints',1,...
    'Weight',1); %

%% matching

tol=1e-6;
[arc1,~,currentvalues]=atmatch(arc,Variab,Constr,tol,100,3,@lsqnonlin);%'fminsearch',3);%

return





function RING_matched=matchingDBA(RING,bxDb,byDb,DDb,Qx,...
    indQF,indQD,indQFM,indQDM)

V=atVariableBuilder(RING,...
    {indQF,indQD,indQDM,indQFM},{{'PolynomB',{1,2}}});

c1=atlinconstraint(indQFM(2),...
    {{'beta',{1}},{'beta',{2}}},...
    [bxDb,byDb],...
    [bxDb,byDb],...
    [1 1]);

c2=atlinconstraint(1,...
    {{'Dispersion',{1}},{'tune',{1}}},...
    [DDb,Qx],...
    [DDb,Qx],...
    [1 1]);

c=[c1,c2];

RING_matched=atmatch(RING,V,c,10^-6,1000,0,@lsqnonlin);%


return
