function b=StretchPertArray(a)

if ~isfield(a,'dk')
    a.dk=1e-5;
end

if ~isfield(a,'delta')
    a.delta=0;
end  

if iscell(a.perturbation)
b=struct(...
    'perturbation',{a.perturbation},...
    'index',num2cell(a.index),...
    'delta',a.delta,...
    'dk',a.dk);
else
b=struct(...
    'perturbation',a.perturbation,...
    'index',num2cell(a.index),...
    'delta',a.delta,...
    'dk',a.dk);    
end

return