Description of jmat
Home > atmat > atphysics > LinearOptics > jmat.m
jmat
PURPOSE
JMAT Compute antisymmetric Matrix [O 1; -1 0]
SYNOPSIS
function mat=jmat(dim)
DESCRIPTION
 JMAT Compute antisymmetric Matrix [O 1; -1 0]
  INPUTS
    1. dim - 1,2,3 Dimension of the sqare matrix
  OUPUTS
    2. mat - Antisymmetric block Matrix [O 1; -1 0]
  See also symplectify
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
amat find A matrix from one turn map matrix T such that:
find_betaoids [H1 H2 H3]=find_betaoids(A)
find_inv_G This function computes the invariants of a one turn map matrix.
SOURCE CODE
function mat=jmat(dim)
% JMAT Compute antisymmetric Matrix [O 1; -1 0]
%
%  INPUTS
%    1. dim - 1,2,3 Dimension of the sqare matrix
%
%  OUPUTS
%    2. mat - Antisymmetric block Matrix [O 1; -1 0]
%
%  See also symplectify
S2 = [0 1; -1 0];
if(dim==1)
    mat=[0 1;-1 0];
elseif(dim==2)
    mat = blkdiag(S2,S2);
elseif(dim==3)
    mat = blkdiag(S2,S2,S2);
else
    Error('Dim is 1, 2 or 3')
end