% Touschek liftime and apertures
%
%   Contents file for TOUSCHEKPIWINSKI and its subfolders.
%   
%   TOUSCHEKPIWINSKI
%   MomAperture_allRing       - Returns positive and negative momentum aperture
%   MomAperture_Project2Start - Calculates the local momentum aperture
%   momentum_aperture_at      - Recursively offsets the particle energy and checks
%   simpletestToucheckLT      - Simple example of use of toucheck lifetime formula:
%   TLT_IntPiw                - Integral in Piwinski Formula for the Lifetime
%   TLT_IntPiw_k              - Integral in Piwinski Formula for the Lifetime with u=tan^2(k)
%   TouschekPiwinskiLifeTime  - Function [Tl,contributionsTL]=TouschekPiwinskiLifeTime(ring,dpp,Ib,...)
%    
%   This file was generated by updateContents.m on 26 Jun 2025 15:10:56.
