Description of getflag
Home > atmat > lattice > getflag.m
getflag
PURPOSE
GETFLAG Check the presence of a flag in an argument list
SYNOPSIS
function [flag,opts] = getflag(opts,optname)
DESCRIPTION
GETFLAG Check the presence of a flag in an argument list
OPTION=GETFLAG(ARGS,OPTNAME)
   Return a logical value indicating the presence of the flag name in the
   argument list. Flag names are case insensitive.
ARGS:      Argument list (cell array)
OPTNAME:    Name of the desired option (string)
[OPTION,NEWARGS]=GETFLAG(ARGS,OPTNAME)
           Returns the argument list after removing the processed flag
Example:
function testfunc(varargin)
[optflag,args]=getflag(varargin,'option');     % Extract an optional flag
[range,args]=getoption(args,'Range', 1:10);    % Extract a keyword argument
[width, height]=getargs(args,{210,297});       % Extract positional arguments
Dee also GETOPTION, GETARGS
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
atfastring ATFASTRING Generate simplified AT structures
entrancefields ENTRANCEFIELDS() Return the list of field names affecting the element entrance
exitfields EXITFIELDS() Return the list of field names affecting the element exit
SOURCE CODE
function [flag,opts] = getflag(opts,optname)
%GETFLAG Check the presence of a flag in an argument list
%
%OPTION=GETFLAG(ARGS,OPTNAME)
%   Return a logical value indicating the presence of the flag name in the
%   argument list. Flag names are case insensitive.
%
%ARGS:      Argument list (cell array)
%OPTNAME:    Name of the desired option (string)
%
%[OPTION,NEWARGS]=GETFLAG(ARGS,OPTNAME)
%           Returns the argument list after removing the processed flag
%
%Example:
%
%function testfunc(varargin)
%
%[optflag,args]=getflag(varargin,'option');     % Extract an optional flag
%[range,args]=getoption(args,'Range', 1:10);    % Extract a keyword argument
%[width, height]=getargs(args,{210,297});       % Extract positional arguments
%
%Dee also GETOPTION, GETARGS
ok=strcmpi(optname,opts);
flag=any(ok);
opts=opts(~ok);
end