function I=TLT_IntPiw(u,um,B1,B2) 
% integral in Piwinski Formula for the Lifetime


%   in case the Bessel function has too large value (more than 10^251) it 
%   is substituted by its exponential approximation:
%   I_0(x)~exp(x)/sqrt(2*pi*x)

if B2*u<500
    I=(...
        (...
       ((2+1./u).^2).*(((u./um)./(1+u))-1) +...
      1 - ...
      sqrt((1+u))./sqrt((u./um)) -...
      1./(2.*u).*(4+(1./u)).*log((u./um)./(1+u))...
      ).*exp(-B1.*u).*besseli(0,B2.*u).*sqrt(u)./sqrt((1+u))...
      );
else
    I=(...
        (...
       ((2+1./u).^2).*(((u./um)./(1+u))-1) +...
      1 - ...
      sqrt((1+u))./sqrt((u./um)) -...
      1./(2.*u).*(4+(1./u)).*log((u./um)./(1+u))...
      ).*exp(B2.*u-B1.*u)./sqrt(2*pi*B2.*u).*sqrt(u)./sqrt((1+u))...
      );
end

return