% TUNEANDCHROMATICITY
% See also 
% 
%   Contents file for TUNEANDCHROMATICITY and its subfolders.
%   
%   TUNEANDCHROMATICITY
%   findtune  - Get the tune value from turn by turn positions
%   fitchrom2 - Fits chromaticity  of THERING using 2 sextupole families
%   fittune2  - Fits linear tunes of THERING using 2 quadrupole families
%   intfft    - Calculates the tune from interpolated FFT of the trajectory
%   tunechrom - Computes linear tunes and chromaticities
%    
%   This file was generated by updateContents.m on 06 Nov 2023 at 14:58:12.
