Description of findspos
Home > atmat > atphysics > findspos.m
findspos
PURPOSE
FINDSPOS returns longitudinal positions of accelerator lattice elements.
SYNOPSIS
function spos = findspos(LINE,REFPTS)
DESCRIPTION
FINDSPOS returns longitudinal positions of accelerator lattice elements.
  Return value is a vector of positions S at the entrance of each element
  specified by its number in REFPTS
 Note: REFPTS is an array of increasing indexes that
   select elements from range 1 to length(LATTICE)+1.
   REFPTS is allowed to go 1 point beyond the
   number of elements. In this case the last point is
   the EXIT of the last element. If LATTICE is a RING
   it is also the entrance of the first element after 1 turn.
   Note:
   1. Use findspos(RING,1:length(RING)) for to find
      longitudinal position of all elements
   2. Use findspos(LINE,length(LINE)+1) to find the
      total physical length
   3. If line is a closed ring, exit of the last element
      is also the entrance to the first.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
atlinopt ATLINOPT performs linear analysis of the COUPLED lattices
findorbit6 FINDORBIT6 finds closed orbit in the full 6-d phase space
linopt LINOPT performs linear analysis of the COUPLED lattices
mcf MCF momentum compaction factor
plotbeta PLOTBETA plots UNCOUPLED! beta-functions
plotcod PLOTCOD Closed Orbit Distortion
twissline TWISSLINE calculates linear optics functions for an UNCOUPLED transport line
twissring TWISSRING calculates linear optics functions for an UNCOUPLED ring
SOURCE CODE
function spos = findspos(LINE,REFPTS)
%FINDSPOS returns longitudinal positions of accelerator lattice elements.
%  Return value is a vector of positions S at the entrance of each element
%  specified by its number in REFPTS
%
% Note: REFPTS is an array of increasing indexes that
%   select elements from range 1 to length(LATTICE)+1.
%   REFPTS is allowed to go 1 point beyond the
%   number of elements. In this case the last point is
%   the EXIT of the last element. If LATTICE is a RING
%   it is also the entrance of the first element after 1 turn.
%
%   Note:
%   1. Use findspos(RING,1:length(RING)) for to find
%      longitudinal position of all elements
%   2. Use findspos(LINE,length(LINE)+1) to find the
%      total physical length
%   3. If line is a closed ring, exit of the last element
%      is also the entrance to the first.
NE=length(LINE);
L=zeros(1,NE+1);
for k=1:NE
    if isfield(LINE{k},'Length')
        ll=LINE{k}.Length;
    else
        ll=0;
    end
    L(k+1)=L(k)+ll;
end;
spos=L(REFPTS);