function plot_emailresults(fma)

h = fma_lib('plotfm',fma);
print(['-f' num2str(h.difhandle)],'-dpdf','-adobecset','email_DA.pdf');
print(['-f' num2str(h.tunehandle)],'-dpdf','-adobecset','email_FM.pdf');
fma
summarystring = {...
    sprintf('Lattice file: %s\n',fma.latticefile);...
    sprintf('Start and end: %s    %s\n',fma.starttime,fma.endtime);...
    sprintf('total time: %f\n',fma.totaltime);...
    sprintf('nturns: %d   %d\n',fma.nturn1, fma.nturn2);...
    sprintf('Comments: %s\n',fma.comments)};

attachemnts = {'email_DA.pdf', 'email_FM.pdf'};

sendmail('eugene.tan@synchrotron.vic.gov.au',['Results for ' fma.resultsfile],summarystring,attachemnts);