% COLLECTIVEEFFECTS
% See also 
% 
%   Contents file for COLLECTIVEEFFECTS and its subfolders.
%   
%   COLLECTIVEEFFECTS
%   atbeam  - Generates a particle distribution according to a sigma matrix
%   atsigma - Constructs a beam sigma matrix 2x2 4x4 or 6x6
%    
%   This file was generated by updateContents.m on 06 Nov 2023 at 14:58:12.
