% Collective Effects
%
%   Contents file for COLLECTIVEEFFECTS and its subfolders.
%   
%   COLLECTIVEEFFECTS
%   atbeam  - Generates a particle distribution according to a sigma matrix
%   atsigma - Constructs a beam sigma matrix 2x2 4x4 or 6x6
%    
%   This file was generated by updateContents.m on 27 Jun 2025 11:27:19.
