% VACUUMLIFETIME
% See also 
% 
%   Contents file for VACUUMLIFETIME and its subfolders.
%   
%   VACUUMLIFETIME
%   VacLifetimeResidualGass - Coloumb scattering and residual gas Bremsstrahlung Cross sections are
%    
%   This file was generated by updateContents.m on 06 Nov 2023 at 14:58:13.
