Description of findcells
Home > atmat > lattice > findcells.m
findcells
PURPOSE
FINDCELLS performs a search on MATLAB cell arrays of structures
SYNOPSIS
function index = findcells(CELLARRAY, field, varargin)
DESCRIPTION
FINDCELLS performs a search on MATLAB cell arrays of structures
 INDEX = FINDCELLS(CELLARRAY, 'field')
   returns indexes of elements that have a field named 'field'
 INDEX = FINDCELLS(CELLARRAY, 'field', VALUE)
   returns indexes of elements whose field 'field'
   is equal to VALUE1, VALUE2, ... or VALUEN. Where VALUE can either be
   character strings or a number. If its a character string REGULAR
   expressions can be used.
 Example:
   findcells(THERING,'Length',0, 0.2);  % will match elements of
                                          lengths 0 and 0.2
   findcells(THERING,'FamName','SFA','SDA');
 See also ATGETCELLS, GETCELLSTRUCT, SETCELLSTRUCT, REGEXPI
CROSS-REFERENCE INFORMATION
This function calls:
atgetcells ATGETCELLS performs a search on MATLAB cell arrays of structures
This function is called by:
ataddmpoleerrors2 ataddmpoleerrors2 adds multipole errors to certain elements of ring and
atmakefielderrstruct MAKERNDFIELDERRS will create a field error data structure
atparamgroup PARAMETER GROUP in AT is a general way
combinebypassmethod COMBINEBYPASSMETHOD combines adjacent elements that have the same specified pass method
combinelinear45 COMBINELINEAR45 combines adjacent elements that use 4-by-5 PassMethods
findtags FINDTAGS looks for string matches in 'Tag' field of AT lattice elements
mkparamgroup MKPARAMGROUP simplifies creation of AT parameter groups
settags SETTAGS sets the 'Tag' field in AT lattice elements
SOURCE CODE
function index = findcells(CELLARRAY, field, varargin)
%FINDCELLS performs a search on MATLAB cell arrays of structures
%
% INDEX = FINDCELLS(CELLARRAY, 'field')
%   returns indexes of elements that have a field named 'field'
%
% INDEX = FINDCELLS(CELLARRAY, 'field', VALUE)
%   returns indexes of elements whose field 'field'
%   is equal to VALUE1, VALUE2, ... or VALUEN. Where VALUE can either be
%   character strings or a number. If its a character string REGULAR
%   expressions can be used.
%
% Example:
%   findcells(THERING,'Length',0, 0.2);  % will match elements of
%                                          lengths 0 and 0.2
%   findcells(THERING,'FamName','SFA','SDA');
%
% See also ATGETCELLS, GETCELLSTRUCT, SETCELLSTRUCT, REGEXPI
index=reshape(find(atgetcells(CELLARRAY,field,varargin{:})),1,[]);