% ATINTEGRATORS
% See also 
% 
%   Contents file for ATINTEGRATORS and its subfolders.
%   
%   ATINTEGRATORS
%   aperture                   - Creates a aperture element in old a AT version (Obsolete)
%   BndStrMPoleSymplectic4Pass - .m Help file for BndStrMPoleSymplectic4Pass.c
%   corrector                  - Creates a corrector element in old a AT version (Obsolete)
%   drift                      - Creates a drift element in old a AT version (Obsolete)
%   DriftPass                  - - Integrator for Drift spaces
%   ExactHamiltonianPass       - .m Help file for ExactHamiltonianPass.c
%   GWigSymplecticPass         - #ok<STOUT>
%   GWigSymplecticRadPass      - #ok<STOUT>
%   hmonitor                   - Creates a horizontal monitor element in old AT version (Obsolete)
%   idtable                    - (fname, Nslice, filename, Energy, method)
%   idtable_global             - IDTABLE Creates a RADIA-Map based element
%   marker                     - Creates a marker element in old AT version (Obsolete)
%   mChangeRefPass             - Change the reference energy by scaling
%   mDriftPass                 - Example of pass method in matlab
%   mhdrload_bis               - Loads data from an ASCII file containing multiple text
%   mIdentityPass              - MDRIFTPASS - example of pass method in matlab
%   monitor                    - Creates a monitor element in old AT versions (Obsolete)
%   multipole                  - Creates a thick multipole element in old AT versions (Obsolete)
%   passmethodlist             - Utility function for MATLAB Compiler
%   passmethods                - Returns a list of available AT passmethod functions in
%   quadrupole                 - Creates a quadrupole element in old AT version (Obsolete)
%   rbend                      - Creates a rectangular bend in old AT version (Obsolete)
%   rbend2                     - Creates rectangular bend with dipole fringe field  in old AT versions (Obsolete)
%   rbend3                     - Creates a rectangular bend with different fringe fields at entrance
%   rfcavity                   - Creates a RF cavity in older AT version
%   sbend                      - Creates a sector bend element in old AT versions (Obsolete)
%   sextupole                  - Creates a sextupole element in old AT versions (Obsolete)
%   skewquad                   - Creates a skewquad element (alias to multipole) in old AT version (Obsolete)
%   solenoid                   - Creates a solenoid element in old AT versions (Obsolete)
%   vmonitor                   - Creates a vertical monitor element in old AT version (Obsolete)
%   wiggler                    - (fname, Ltot, Lw, Bmax, Nstep, Nmeth, By, Bx, method,energy)
%    
%   This file was generated by updateContents.m on 06 Nov 2023 at 14:58:13.
