% ATDEMOS
% See also 
% 
%   Contents file for ATDEMOS and its subfolders.
%   
%   ATDEMOS/ATFASTRING
%   testatfastring         - Demo of using atfastring for fast tracking
%   
%   ATDEMOS/ATMATCHEXAMPLES/BUMP
%   run_BumpFit            - Fit a bump using correctors
%   
%   ATDEMOS/ATMATCHEXAMPLES/EXAMPLEATMATCH
%   betx                   - Get value of betx for  Seq(indx)
%   bety                   - Get value of bety for  Seq(indx)
%   dispx                  - Get value of horizontal dispersion for  Seq(indx)
%   getDispersion          - Function [dx,dy]=getDispersion(THERING,bpmindx)
%   mux
%   runtotest_atmatch      - Macro match dba test lattice beta functions and dispersion using
%   VaryQuadFam
%   
%   ATDEMOS/ATMATCHEXAMPLES/MATCHCHROMATICITY
%   run_matchChromaticity  - Match chrmaticity
%   
%   ATDEMOS/GUI
%   atslider               - Is an example of a GUI control of multiple parameters in THERING
%   demoknob               - Illustrates the use of MATLAB GUI controls with AT
%   
%   ATDEMOS/IDMODELING
%   add_ID                 - Adds IDelem at the beginning and subtracts the length from
%   trackWithU35KickMap    - Read in ESRF lattice
%   
%   ATDEMOS/OPTICSANDBEAMSIZES
%   latticedemo            - Self-running tutorial
%   linoptdemo             - Script illustrates the use of LINOPT
%   ohmienvelopedemo       - Illustrates the use of OHMIENVELOPE function
%   
%   ATDEMOS/RESPONSEMATRIX
%   findrespmdemo          - Response matrix demo
%   
%   ATDEMOS/TRACKING
%   generateTrackData      - Give some initial coordinates.  Track through sample lattices
%   test_openmp            - Test the perfoemance of OpenMP
%   testTracking           - Test results of tracking against values previously computed
%   trackingdemo           - Self-running tutorial
%   trackMultipleParticles - Time the tracking of multiple particles
%   
%   ATDEMOS/TRACKWITHIMPEDANCE
%   makeBBR                - SI units;
%   testTrackBBR           - Create a fast ring from ESRF lattice
%    
%   This file was generated by updateContents.m on 05 Nov 2023 at 22:34:11.
