% Updates Contents.m of AT directories
% For ATROOT: Contents will include subdirectories
% For other subdirectories, policiy is defined in case by case

ATROOT = fileparts(atroot);
OLDDIR = pwd;

%Selects directories where to creat a Contents
listOfFolderNames={
    fullfile(ATROOT,'atmat', 'atdemos'), ...
    fullfile(ATROOT,'atmat', 'atgui'), ...
    fullfile(ATROOT,'atmat', 'atmatch'), ...
    fullfile(ATROOT,'atmat', 'atphysics'), ... 
    fullfile(ATROOT,'atmat', 'atplot'), ...
    fullfile(ATROOT,'atmat', 'attrack'), ...
    fullfile(ATROOT,'atmat', 'pubtools'), ...
    fullfile(ATROOT,'atmat', 'lattice'), ...
    fullfile(ATROOT,'atmat', 'lattice', 'Converters'), ...
    fullfile(ATROOT,'atmat', 'lattice','element_creation'), ...
    fullfile(ATROOT,'machine_data'), ...
    fullfile(ATROOT,'atintegrators'), ...
    fullfile(ATROOT,'atmat', 'pubtools'), ...
    fullfile(ATROOT,'atmat', 'pubtools', 'LatticeTuningFunctions'), ...
    fullfile(ATROOT,'atmat'), ...
    fullfile(ATROOT), ...
    };
% Generates specific Contents
for k=1:length(listOfFolderNames)
    cd(listOfFolderNames{k})
    fprintf('Updating Contents of folder %s\n', cd);
    updateContents(cd);   
end

cd(OLDDIR);

clear OLDIR ATROOT