% Updates Contents.m of AT directories
% For ATROOT: Contents will include subdirectories
% For other subdirectories, policiy is defined in case by case

ATROOT = fileparts(atroot);
OLDDIR = pwd;

%Selects directories where to create a Contents
listOfFolderNames={
    fullfile(ATROOT,'atmat', 'atdemos'), ...
    fullfile(ATROOT,'atmat', 'atgui'), ...
    fullfile(ATROOT,'atmat', 'atmatch'), ...
    fullfile(ATROOT,'atmat', 'atutils'), ... 
    fullfile(ATROOT,'atmat', 'atphysics'), ... 
    fullfile(ATROOT,'atmat', 'atphysics', 'CollectiveEffects'), ... 
    fullfile(ATROOT,'atmat', 'atphysics', 'LinearOptics'), ... 
    fullfile(ATROOT,'atmat', 'atphysics', 'LongitudinalDynamics'), ... 
    fullfile(ATROOT,'atmat', 'atphysics', 'Orbit'), ... 
    fullfile(ATROOT,'atmat', 'atphysics', 'ParameterSummaryFunctions'), ... 
    fullfile(ATROOT,'atmat', 'atphysics', 'TouschekPiwinski'), ... 
    fullfile(ATROOT,'atmat', 'atphysics', 'TuneAndChromaticity'), ... 
    fullfile(ATROOT,'atmat', 'atphysics', 'Radiation'), ... 
    fullfile(ATROOT,'atmat', 'atphysics', 'NonLinearDynamics'), ... 
    fullfile(ATROOT,'atmat', 'atphysics', 'nafflib'), ... 
    fullfile(ATROOT,'atmat', 'atplot'), ...
    fullfile(ATROOT,'atmat', 'atplot', 'plotfunctions'), ...
    fullfile(ATROOT,'atmat', 'attrack'), ...
    fullfile(ATROOT,'atmat', 'lattice'), ...
    fullfile(ATROOT,'atmat', 'lattice', 'Converters'), ...
    fullfile(ATROOT,'atmat', 'lattice','element_creation'), ...
    fullfile(ATROOT,'atmat', 'lattice','survey'), ...
    fullfile(ATROOT,'machine_data'), ...
    fullfile(ATROOT,'atintegrators'), ...
    fullfile(ATROOT,'atmat', 'pubtools'), ...
    fullfile(ATROOT,'atmat', 'pubtools', 'LatticeTuningFunctions'), ...
    fullfile(ATROOT,'atmat', 'pubtools', 'VacuumLifetime'), ...
    fullfile(ATROOT,'atmat', 'pubtools', 'distance2curve'), ...
    fullfile(ATROOT,'atmat', 'pubtools', 'haissinski'), ...
    fullfile(ATROOT,'atmat', 'pubtools', 'lattice_tools'), ...
    fullfile(ATROOT,'atmat', 'pubtools', 'local_lattice_params'), ...
    fullfile(ATROOT,'atmat', 'pubtools', 'create_elems'), ...
    fullfile(ATROOT,'atmat'), ...
    fullfile(ATROOT), ...
    };
% Generates specific Contents
for k=1:length(listOfFolderNames)
    cd(listOfFolderNames{k})
    fprintf('Updating Contents of folder %s\n', cd);
    updateContents(cd);   
end

myheaderstr = '% ';
dlmwrite('Contents.m',[myheaderstr 13 10 fileread('Contents.m')],'delimiter','');
myheaderstr = '% Version 2.5.0 (atcollab) 05-Nov-2023';
dlmwrite('Contents.m',[myheaderstr 13 10 fileread('Contents.m')],'delimiter','');
myheaderstr = '% Accelerator Toolbox';
dlmwrite('Contents.m',[myheaderstr 13 10 fileread('Contents.m')],'delimiter','');

cd(OLDDIR);

clear OLDIR ATROOT