Description of CurlyH
Home > atmat > pubtools > plotfunctions > CurlyH.m
CurlyH
PURPOSE
TD=twissring(RING,dp,ind);
SYNOPSIS
function [H,Hv]=CurlyH(RING,dp,ind)
DESCRIPTION
TD=twissring(RING,dp,ind);
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
plEmitContrib plots H/rho³ at every dipole
plotB0curlyh
plotbetadispcurlyh
plotsqrtbetadispcurlyh
SOURCE CODE
function [H,Hv]=CurlyH(RING,dp,ind)
%TD=twissring(RING,dp,ind);
[TD,~,~]=atlinopt(RING,dp,ind);
 B = cat(1,TD.beta);
 A = cat(1,TD.alpha);
 %[D,Dv] = getDispersion(RING,ind);
 %[Dp,Dpv] = getDispersionAngle(RING,ind);
 DD = cat(2,TD.Dispersion);
 D=DD(1,:);
 Dv=DD(3,:);
 Dp=DD(2,:);
 Dpv=DD(4,:);
 G=(1+A(:,1).^2)./B(:,1);
 Gv=(1+A(:,2).^2)./B(:,2);
 H=B(:,1).*Dp'.*Dp' + 2*A(:,1).*D'.* Dp' + G.*D'.* D';
 Hv=B(:,2).*Dpv'.*Dpv' + 2*A(:,2).*Dv'.* Dpv' + Gv.*Dv'.* Dv';