% RADIATION
% See also 
% 
%   Contents file for RADIATION and its subfolders.
%   
%   RADIATION
%   atdisable_6d           - Switches radiation and cavity off
%   atenable_6d            - Switches RF and radiation on
%   atenergy               - Gets the lattice energy
%   atgetU0                - Computes Energy loss per turn in eV 
%   atradoff               - Obsolete: switches RF and radiation off
%   atradon                - Obsolete: switches RF and radiation on
%   atsetenergy            - (ring,Energy) sets the Energy field in all
%   attapering             - Scale magnet strengths
%   check_6d               - Check the presence of longitudinal motion in a lattice
%   check_radiation        - Obsolete: check the radiation state of a ring
%   DipoleRadiation        - Compute the radiation integrals in dipoles
%   ElementRadiation       - - Compute the radiation integrals in dipoles
%   ElossRadiation         - Compute the radiation integrals in EnergyLoss elements
%   findelemraddiffm
%   findmpoleraddiffmatrix - #ok<STOUT>
%   findthickmpoleraddiffm
%   findthinmpoleraddiffm
%   getclass_6d            - Private. Guess class for 6d motion
%   ohmienvelope           - Calculates equilibrium beam envelope in a
%   quantumDiff            - Compute the radiation-diffusion matrix
%   radiationoff           - Turns classical radiation  OFF
%   radiationon            - Turns classical radiation  ON
%   thickmpoleraddiffm     - FINDTHICKMPOLERADDIFFM
%   thinmpoleraddiffm      - FINDTHINMPOLERADDIFFM
%   WigglerRadiation       - Compute the radiation integrals in wigglers
%    
%   This file was generated by updateContents.m on 06 Nov 2023 at 14:58:12.
