% HAISSINSKI
% See also 
% 
%   Contents file for HAISSINSKI and its subfolders.
%   
%   HAISSINSKI
%   blength
%   fitgaussian    - GAUSSIAN_PARAM FITERR GAUSSFIT SIGERROR]= FITGAUSSIAN(DATA,[property_value_pair]);
%   plothaissinski - [z lambda sigma mu] = HASSINSKYFIT(SIGMA0, R, L)
%   Qval           - Gives the unitless Q parameter needed to compute the
%    
%   This file was generated by updateContents.m on 06 Nov 2023 at 14:58:13.
