Description of bpm_process
Home > atmat > pubtools > LatticeTuningFunctions > errors > bpm_process.m
bpm_process
PURPOSE
UNTITLED3 Summary of this function goes here
SYNOPSIS
function bpmreading = bpm_process(bpmorbit,rel,tel,trand)
DESCRIPTION
UNTITLED3 Summary of this function goes here
   Detailed explanation goes here
 by L.F. Jun 2016, ESRF,  K:\machine\matlab\atlf
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
findorbit4Err findorbit4Err Gets 4x4 closed orbit with BPM errors
findorbit6Err findorbit6 with bpm reading errors
findtrajectory6Err [t 6xNbpm array of trajectory
SUBFUNCTIONS
function x=process(x0,rel,tel,trand)
SOURCE CODE
function bpmreading = bpm_process(bpmorbit,rel,tel,trand)
%UNTITLED3 Summary of this function goes here
%   Detailed explanation goes here
% by L.F. Jun 2016, ESRF,  K:\machine\matlab\atlf
bp=cellfun(@process,mat2cell(bpmorbit,2,ones(1,size(bpmorbit,2))),rel,tel,trand,'UniformOutput',false);
bpmreading=cat(2,bp{:});
    function x=process(x0,rel,tel,trand)
        x=rel*x0 + tel + trand.*randn(2,1);
    end
end