Description of findorbit6Err
Home > atmat > pubtools > LatticeTuningFunctions > errors > findorbit6Err.m
findorbit6Err
PURPOSE
findorbit6 with bpm reading errors
SYNOPSIS
function orbit = findorbit6Err(RING, indbpm,varargin)
DESCRIPTION
 findorbit6 with bpm reading errors
see also findorbit6 bpm_process bpm_matrices
CROSS-REFERENCE INFORMATION
This function calls:
bpm_matrices BPM_MATRICES Computes the transformation matrices for the given BPMs
bpm_process UNTITLED3 Summary of this function goes here
This function is called by:
finddispersion6Err FINDDISPERSION6ERR Gets 6D dispersion with bpm reading errors
SOURCE CODE
function orbit = findorbit6Err(RING, indbpm,varargin)
% findorbit6 with bpm reading errors
%
%see also findorbit6 bpm_process bpm_matrices
orbit = findorbit6(RING, indbpm, varargin{:});
% BPM errors used only if class is Monitor
%useind=ismember(indbpm,find(atgetcells(ring,'Class','Monitor')));
useind=1:length(indbpm);
[rel,tel,trand] = bpm_matrices(RING(indbpm(useind)));
bpmreading = bpm_process(orbit([1,3],:),rel,tel,trand);
orbit(1,:)=bpmreading(1,:);
orbit(3,:)=bpmreading(2,:);
return