%Parameter groups
%
%   Contents file for PARAMGROUP and its subfolders.
%   
%   PARAMGROUP
%   atparamgroup      - PARAMETER GROUP in AT is a general way
%   mkparamgroup      - Simplifies creation of AT parameter groups
%   restoreparamgroup - Restores the values of multiple physical
%   saveparamgroup    - Saves the values of multiple physical
%   setparamgroup     - Modifies a group of parameters
%    
%   This file was generated by updateContents.m on 26 Jun 2025 18:29:10.
