function Elem = atinsertiondevicekickmap( fname, ...
                                          method, ...
                                          filename, ...
                                          Normalization_energy, ...
                                          Nslice, ...
                                          length, ...
                                          xkick2, ...
                                          ykick2, ...
                                          xkick1, ...
                                          ykick1, ...
                                          xtable, ...
                                          ytable ...
                                        )
% atinsertiondevicekickmap creates an insertion device kick-map element
% Elem = atinsetiondevicekickmap( fname, ...
%                                 method, ...
%                                 filename, ...
%                                 Normalization_energy, ...
%                                 Nslice, ...
%                                 length, ...
%                                 xkick, ...
%                                 ykick, ...
%                                 xkick1, ...
%                                 ykick1, ...
%                                 xtable, ...
%                                 ytable ...
%                               )
%
% fname     family name
% method    'IdTablePass'
% filename  name of the file used to create the element
% Normalization_energy    energy to which the field table was scaled
% Nslice    number of slices (1 means the wiggler is represented by a
%           single kick in the center of the device).
% length    length of the element
% NumX      number of horizontal points
% NumY      number of vertical points
% xkick     list of x positions
% ykick     list of y positions
% xkick1    ---
% ykick1    ---
% xtable    horizontal plane table
% ytable    vertical plane table
%
% The tracking method is described in
% P. Elleaume, "A new approach to the electron beam dynamics in undulators
% and wigglers", EPAC92.
%
% Returns an element with Class 'InsertionDeviceKickMap'

%------------------
% Modification Log:
% -----------------
% 24-05-2023:  blanco-garcia, added for compatibility with pyat
% 13-11-2023:  blanco-garcia, change of variable names as in Pull Request
%                             https://github.com/atcollab/at/pull/683
%---------------------------------------------------------------------------

Elem.FamName = fname;
Elem.PassMethod = method;
Elem.Filename_in = filename;
Elem.Normalization_energy = Normalization_energy;
Elem.Nslice = Nslice;
Elem.Length= length;
Elem.xtable = xtable;
Elem.ytable = ytable;
Elem.xkick2 = xkick2;
Elem.ykick2 = ykick2;
Elem.xkick1 = xkick1;
Elem.ykick1 = ykick1;
Elem.Class = 'InsertionDeviceKickMap';

return
