% ELEMENT_CREATION
% See also 
% 
%   Contents file for ELEMENT_CREATION and its subfolders.
%   
%   ELEMENT_CREATION
%   ataperture               - Creates a aperture element
%   atbaselem                - Create an AT element structure + various checks
%   atcorrector              - Creates a drift space element with class 'Corrector'
%   atdampMatElem            - Creates an element that applies the global damping matrix
%   atdrift                  - Creates a drift space element with Class 'Drift'
%   atenergyloss             - Creates an energy loss element
%   atidtable                - Creates an ID element
%   atinsertiondevicekickmap - Creates an insertion device kick-map element
%   atM66                    - Create an element applying an arbitrary 6x6 transfer matrix
%   atM66Tijk                - ATM66(FAMNAME,M66,Tijk,PASSMETHOD)
%   atmarker                 - Creates a marker space element
%   atmonitor                - Creates a Beam Position Monitor element with Class 'Monitor'
%   atmultipole              - Creates a multipole element
%   atquadrupole             - Creates a quadrupole element with Class 'Quadrupole'
%   atQuantDiff              - Creates a quantum diffusion element
%   atrbend                  - Creates a rectangular bending magnet element with class 'Bend'
%   atrbendtune              - Set X0ref and RefDZ for rectangular bending magnets
%   atrfcavity               - Creates an rfcavity element with Class 'RFCavity'
%   atringparam              - Creates a RingParameter Element which should go at the beginning of the ring
%   atsbend                  - Creates a sector bending magnet element with class 'Bend'
%   atsextupole              - Creates a sextupole element with class 'Sextupole'
%   atSimpleQuantDiff        - SimpleQuantDiff creates a simple quantum difusion element
%   atskewquad               - Creates a skew quadrupole element with Class 'Multipole'
%   atsolenoid               - Creates a new solenoid element with Class 'Solenoid'
%   atthinmultipole          - Creates a thin multipole element
%   atvariablemultipole      - Creates a variable thin multipole element
%   atwiggler                - Creates a wiggler
%   
%   ELEMENT_CREATION/PRIVATE
%   decodeatargs             - Separates arguments and resources
%    
%   This file was generated by updateContents.m on 06 Nov 2023 at 14:58:13.
