name: Check Version

on:
  push

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11, windows-2019]

    steps:
      - uses: actions/checkout@v3
        with:
          # Necessary to fetch tags and allow setuptools_scm
          # see: https://github.com/pypa/setuptools_scm/issues/480
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Get version
        # Get the version before modifying the repository
        shell: bash
        run: |
          python -m pip install setuptools-scm
          echo "SETUPTOOLS_SCM_PRETEND_VERSION=$(python -m setuptools_scm)" >> $GITHUB_ENV

      - name: Set build configuration
        run: cp githubproject.toml pyproject.toml

      - name: Build wheels
        shell: bash
        run: echo $SETUPTOOLS_SCM_PRETEND_VERSION
